apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obesitrack.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "obesitrack.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "obesitrack.name" . }}
    spec:
      containers:
        - name: obesitrack
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              value: "{{ .Values.env.SECRET_KEY }}"
            - name: DATABASE_URL
              value: "{{ .Values.env.DATABASE_URL }}"
            - name: MODEL_DIR
              value: "{{ .Values.env.MODEL_DIR }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
